Repository ASKnetCommunity/Training, pull requests merged in 2023-12, with the labels that each got.

#144 Improved Tags generation, Font size, Icons, print view and auto-Daybreak
  _layouts/trainingsplan.html
  _sass/trainingsplan-print.sass
  _sass/trainingsplan.sass
  assets/css/trainingsplan-print.min.css
  assets/css/trainingsplan-print.min.css.map
  assets/css/trainingsplan.min.css
  assets/css/trainingsplan.min.css.map
  assets/js/trainingsplan.js
  training.html
Labels: bug, feature, prio1, waiting-for-input, CSS/HTML, JavaScript

#146 New OER Modules and some development tweaks for content curation
  Gemfile
  Gemfile.lock
  _modules/.DS_Store
  _modules/Antifraud_OER_Training.md
  _modules/Reusable_Sanitary_Pads.md
  _modules/creative_hacktivism.md
  _modules/documents_on_github.md
  _modules/inclusive_spaces_for_women.md
  _modules/integration_of_modules_resources.md
  _modules/oers_on_github.md
  _resources/ convivial_technologies.md
  _resources/.template/template.md
  _resources/Chains_and_aveunes_of_fraud_migiation.md
  _resources/Effective_utilization_of_media_spaces.md
  _resources/Types_of_Fraud.md
  _resources/alternative_tools.md
  _resources/case_study_owilla_abiro_mercy.md
  _resources/case_study_stella_nyanzi.md
  _resources/creative_hacktivism_slides.md
  _resources/creative_hacktivist_term.md
  _resources/github_oer_template.md
  _resources/github_repository.md
  _resources/hacktivism_examples.md
  _resources/inclusive_spaces_for_women-exercise.md
  _resources/inclusive_spaces_for_women-slides.md
  _resources/measures_against_fraud.md
  _resources/media_investigations_literacy.md
  _resources/module&resource_intergration.md
  _resources/modules&resources.md
  _resources/reusable_sanitary_pads.md
  _resources/strategies_discussions_co-creation.md
  _resources/template_code.md
  assets/img/modules/asktraining_integration.png
  assets/img/modules/hacktivism_cover.jpg
  assets/img/modules/inclusive_space_women.png
Labels: prio1, content-submit

#164 feat: add new layout design
  _layouts/trainingsplan.html
  _sass/trainingsplan-print.sass
  _sass/trainingsplan.sass
  assets/css/trainingsplan-print.min.css
  assets/css/trainingsplan-print.min.css.map
  assets/css/trainingsplan.min.css
  assets/css/trainingsplan.min.css.map
  assets/js/trainingsplan.js
  training.html
Labels: feature
