Repository ASKnetCommunity/Training, pull requests merged in 2023-10, with the labels that each got.

#81 fix: time edit for multiple breaks
  assets/js/index.js
Labels: bug

#89 Add field "trainer's notes"
  _layouts/trainingsplan.html
  assets/js/index.js
  training.html
Labels: feature

#97 Development changes of the code ready for deployment
  Gemfile.lock
  _layouts/trainingsplan.html
  _resources/.template/template.md
  _resources/EJN_5_Point_test_for_hate_speech_video.md
  _resources/SafeDigitasSpaces.md
  _resources/askotec.md
  _resources/askotecintro.md
  _resources/bmc.md
  _resources/code_of_conduct.md
  _resources/communityrepairsetup.md
  _resources/counter_hate_speech_online.md
  _resources/defyhatenow_boardgame.md
  _resources/defyhatenow_boardgame_instructions.md
  _resources/defyhatenow_facilitator_notes.md
  _resources/defyhatenow_field_guide_c1.md
  _resources/defyhatenow_field_guide_c2.md
  _resources/defyhatenow_field_guide_c3.md
  _resources/defyhatenow_field_guide_c5.md
  _resources/defyhatenow_field_guide_c6.md
  _resources/diy_water_filter_setup.md
  _resources/diy_water_filter_tools&materials.md
  _resources/drinking_contaminated_water.md
  _resources/ethical_journalism_guide.md
  _resources/github_image_integration
  _resources/github_introduction.md
  _resources/github_oer_template.md
  _resources/ledlight.md
  _resources/logframe.md
  _resources/mental_health_trauma.md
  _resources/mmn_boardgame.md
  _resources/mmn_rumour_cards.md
  _resources/oc.md
  _resources/odg.md
  _resources/ohg.md
  _resources/open-file-formats.md
  _resources/openguides.md
  _resources/openworkshopsetup.md
  _resources/os-glossary.md
  _resources/os-licensing.md
  _resources/os-spiral.md
  _resources/solarcharger.md
  _resources/stop_disinformation.md
  _resources/toc.md
  _resources/why-open.md
  assets/js/index.js
  training.html
Labels: bug, feature, prio1, CSS/HTML, JavaScript
